version: 2

project_name: fleet

builds:
  - id: fleet
    main: ./cmd/fleet
    binary: fleet
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ignore:
      - {goos: darwin, goarch: arm}
      - {goos: windows, goarch: arm}
    ldflags:
      - -s -w -X github.com/cenvero/fleet/internal/version.Version={{.Version}}
    flags: [-trimpath]

  - id: fleet-agent
    main: ./cmd/fleet-agent
    binary: fleet-agent
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ignore:
      - {goos: darwin, goarch: arm}
      - {goos: windows, goarch: arm}
    ldflags:
      - -s -w -X github.com/cenvero/fleet/internal/version.Version={{.Version}}
    flags: [-trimpath]

archives:
  - id: fleet-archive
    ids: [fleet]
    formats: [tar.gz]
    format_overrides:
      - {goos: windows, formats: [zip]}
    name_template: "fleet_{{ .Version }}_{{ .Os }}_{{ if eq .Arch \"arm\" }}armv{{ .Arm }}{{ else }}{{ .Arch }}{{ end }}"

  - id: fleet-agent-archive
    ids: [fleet-agent]
    formats: [tar.gz]
    format_overrides:
      - {goos: windows, formats: [zip]}
    name_template: "fleet-agent_{{ .Version }}_{{ .Os }}_{{ if eq .Arch \"arm\" }}armv{{ .Arm }}{{ else }}{{ .Arch }}{{ end }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - id: bound-archive-signatures
    artifacts: archive
    cmd: ./scripts/sign-release-artifact.sh
    signature: "${artifact}.minisig"
    stdin: "{{ .Env.MINISIGN_PASSWORD }}"
    args:
      - "${artifact}"
      - "${signature}"
      - "{{ .Env.MINISIGN_KEY_FILE }}"

homebrew_casks:
  - name: cenvero-fleet
    ids: [fleet-archive]
    binaries: [fleet]
    repository:
      owner: cenvero
      name: homebrew-fleet
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    homepage: https://fleet.cenvero.org
    description: Self-hosted decentralized fleet management platform
    license: AGPL-3.0-or-later
    directory: Casks
    skip_upload: auto
    commit_author:
      name: cenvero-bot
      email: 276044322+cenvero-bot@users.noreply.github.com

release:
  draft: false
  prerelease: auto

snapshot:
  version_template: "{{ .Version }}-next"
