// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Cenvero / Shubhdeep Singh

package core

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"aead.dev/minisign"
	"github.com/cenvero/fleet/internal/logs"
	"github.com/cenvero/fleet/internal/transport"
	"github.com/cenvero/fleet/internal/update"
	"github.com/cenvero/fleet/internal/version"
)

const agentGitHubRepo = "cenvero/fleet"

// AutoInstallAgent downloads and installs fleet-agent on a remote Linux server via SSH,
// creates a systemd service, and marks the agent as managed in the server record.
// If version.Version is "dev", it falls back to uploading a local binary.
func (a *App) AutoInstallAgent(serverName, loginUser, loginKeyPath, loginPassword string, loginPort int, useSudo bool) error {
	server, err := a.GetServer(serverName)
	if err != nil {
		return err
	}

	if loginPort == 0 {
		loginPort = 22
	}
	if loginKeyPath == "" {
		loginKeyPath = filepath.Join(a.ConfigDir, "keys", a.Config.Crypto.PrimaryKey)
	}

	sudo := ""
	if useSudo {
		sudo = "sudo "
	}

	pubKeyData, err := os.ReadFile(filepath.Join(a.ConfigDir, "keys", a.Config.Crypto.PrimaryKey+".pub"))
	if err != nil {
		return fmt.Errorf("read controller public key: %w", err)
	}

	serviceName := defaultServiceName
	agentPort := 2222
	if a.Config.Runtime.DefaultAgentPort > 0 {
		agentPort = a.Config.Runtime.DefaultAgentPort
	}

	serviceUnit, err := buildAgentServiceUnit(server, resolvedBootstrapConfig{
		serviceName:     serviceName,
		agentListenAddr: fmt.Sprintf("0.0.0.0:%d", agentPort),
		agentPort:       agentPort,
	})
	if err != nil {
		return err
	}

	token, err := randomBootstrapToken(rand.Reader)
	if err != nil {
		return fmt.Errorf("generate unpredictable agent install paths: %w", err)
	}
	tempServicePath := "/tmp/cenvero-" + token + ".service"
	tempKeysPath := "/tmp/cenvero-" + token + ".keys"
	tempScriptPath := "/tmp/cenvero-" + token + ".sh"

	uploads := []BootstrapUpload{
		{Path: tempServicePath, Mode: 0o600, Content: []byte(serviceUnit)},
		{Path: tempKeysPath, Mode: 0o644, Content: pubKeyData},
	}

	var installScript string
	if version.Version == "dev" {
		// Development build: upload local binary
		agentBinaryPath, err := resolveAgentBinaryPath("")
		if err != nil {
			return fmt.Errorf("dev build: %w", err)
		}
		binaryData, err := os.ReadFile(agentBinaryPath) // #nosec G304 -- path is generated by the verified release download staging flow
		if err != nil {
			return fmt.Errorf("read agent binary: %w", err)
		}
		tempBinPath := "/tmp/cenvero-" + token + ".bin"
		uploads = append(uploads, BootstrapUpload{
			Path:    tempBinPath,
			Mode:    0o700,
			Content: binaryData,
		})
		installScript = buildLocalBinaryInstallScript(server, sudo, serviceName, tempBinPath, tempServicePath, tempKeysPath, tempScriptPath)
	} else {
		// Release builds never ask the remote host to trust and execute an unchecked
		// network download. The controller downloads the complete supported Linux
		// matrix, verifies each archive against the embedded minisign key, mandatory
		// SHA-256, exact version/target URL, size, and trusted comment, then uploads
		// only the extracted binaries over the already host-key-pinned SSH channel.
		binaries, err := downloadVerifiedAgentBinaries(context.Background(), version.Version, nil)
		if err != nil {
			return fmt.Errorf("verify agent release artifacts: %w", err)
		}
		tempBins := make(map[string]string, len(binaries))
		for _, target := range agentLinuxTargets {
			tempPath := "/tmp/cenvero-" + token + "-" + target.arch + ".bin"
			tempBins[target.name] = tempPath
			uploads = append(uploads, BootstrapUpload{Path: tempPath, Mode: 0o700, Content: binaries[target.name]})
		}
		installScript = buildVerifiedBinaryInstallScript(server, sudo, serviceName, tempBins, tempServicePath, tempKeysPath, tempScriptPath)
	}

	uploads = append(uploads, BootstrapUpload{
		Path:    tempScriptPath,
		Mode:    0o700,
		Content: []byte(installScript),
	})

	executor := sshBootstrapExecutor{networkDialContext: a.NetworkDialContext}
	req := BootstrapRequest{
		Address:        server.Address,
		Port:           loginPort,
		User:           loginUser,
		PrivateKeyPath: loginKeyPath,
		Password:       loginPassword,
		KnownHostsPath: filepath.Join(a.ConfigDir, "keys", "bootstrap_known_hosts"),
		// SECURITY (host-key TOFU): never silently force-replace a pinned host key
		// during a (re-)bootstrap. AcceptNewHostKey maps to forceReplace in the TOFU
		// callback, which on a MISMATCH against an existing pin overwrites it instead
		// of refusing — a MITM during a re-bootstrap could then swap the host key
		// undetected. First-use pinning (no existing pin in bootstrap_known_hosts)
		// always happens regardless of this flag, so leaving it false still pins a
		// brand-new host while REQUIRING a re-presented key to match any existing pin
		// (and refusing with a MITM warning on mismatch). A deliberate re-pin must go
		// through the explicit operator path: `fleet server bootstrap
		// --accept-new-host-key` / `fleet server reconnect --accept-new-host-key`
		// after out-of-band verification, not this silent install flow.
		AcceptNewHostKey: false,
		// On an interactive `fleet server add`, the CLI sets this so a CHANGED host
		// key prompts the operator (y/N) instead of hard-failing — an explicit,
		// non-silent re-pin path. nil keeps the fail-closed default above.
		HostKeyChangedPrompt: a.HostKeyChangedPrompt,
		Uploads:              uploads,
		RunCommand:           "/bin/sh " + shellQuote(tempScriptPath),
	}
	if err := executor.Bootstrap(context.Background(), req); err != nil {
		return fmt.Errorf("agent install: %w", err)
	}

	server.User = "root"
	server.Port = agentPort
	server.Agent = AgentInstall{
		Managed:     true,
		BinaryPath:  defaultAgentBinaryPath,
		ServiceName: serviceName,
		LoginUser:   loginUser,
		LoginPort:   loginPort,
		LoginKey:    loginKeyPath,
		UseSudo:     useSudo,
		UpdatedAt:   time.Now().UTC(),
	}
	if err := a.SaveServer(server); err != nil {
		return err
	}
	return a.AuditLog.Append(logs.AuditEntry{
		Action:   "agent.install",
		Target:   serverName,
		Operator: a.operator(),
		Details:  fmt.Sprintf("version=%s service=%s port=%d login=%s:%d", version.Version, serviceName, agentPort, loginUser, loginPort),
	})
}

// TeardownAgent SSHes to the server using stored login credentials and removes the managed agent.
func (a *App) TeardownAgent(server ServerRecord) error {
	return a.TeardownAgentWithPassword(server, "")
}

// TeardownAgentWithPassword is like TeardownAgent but accepts an explicit password,
// overriding key-based auth. Used by the --via-ssh remove flow.
func (a *App) TeardownAgentWithPassword(server ServerRecord, password string) error {
	if !server.Agent.Managed {
		return nil
	}

	loginUser := server.Agent.LoginUser
	if loginUser == "" {
		return fmt.Errorf("cannot teardown agent on %q: no login user stored (pass --login-user)", server.Name)
	}
	loginPort := server.Agent.LoginPort
	if loginPort == 0 {
		loginPort = 22
	}
	loginKeyPath := server.Agent.LoginKey
	if password != "" {
		loginKeyPath = "" // use password auth
	} else if loginKeyPath == "" {
		loginKeyPath = filepath.Join(a.ConfigDir, "keys", a.Config.Crypto.PrimaryKey)
	}

	sudo := ""
	if server.Agent.UseSudo {
		sudo = "sudo "
	}

	token, err := randomBootstrapToken(rand.Reader)
	if err != nil {
		return fmt.Errorf("generate unpredictable agent teardown path: %w", err)
	}
	tempTeardownPath := "/tmp/cenvero-" + token + ".sh"
	script := buildAgentTeardownScript(server.Agent.ServiceName, sudo, tempTeardownPath)
	executor := sshBootstrapExecutor{networkDialContext: a.NetworkDialContext}
	req := BootstrapRequest{
		Address:        server.Address,
		Port:           loginPort,
		User:           loginUser,
		PrivateKeyPath: loginKeyPath,
		Password:       password,
		KnownHostsPath: filepath.Join(a.ConfigDir, "keys", "bootstrap_known_hosts"),
		// SECURITY (host-key TOFU): same rule as AutoInstallAgent — never silently
		// force-replace a pinned host key. Setting AcceptNewHostKey=false still pins a
		// never-seen host on first use but REQUIRES a matching key when a pin already
		// exists, refusing with a MITM warning on mismatch. A deliberate re-pin goes
		// through the explicit --accept-new-host-key operator path.
		AcceptNewHostKey:     false,
		HostKeyChangedPrompt: a.HostKeyChangedPrompt,
		Uploads: []BootstrapUpload{
			{Path: tempTeardownPath, Mode: 0o700, Content: []byte(script)},
		},
		RunCommand: "/bin/sh " + shellQuote(tempTeardownPath),
	}
	if err := executor.Bootstrap(context.Background(), req); err != nil {
		return fmt.Errorf("agent teardown: %w", err)
	}
	return a.AuditLog.Append(logs.AuditEntry{
		Action:   "agent.teardown",
		Target:   server.Name,
		Operator: a.operator(),
	})
}

// AgentInstallInstructions returns manual installation instructions for non-Linux platforms.
func AgentInstallInstructions(server ServerRecord, mode transport.Mode) string {
	ver := version.Version
	if ver == "dev" {
		ver = "<version>"
	}
	switch mode {
	case transport.ModeReverse:
		enrollSetup := ""
		note := "Add it to your init system to start on boot."
		if server.EnrollSecret != "" {
			enrollSetup = fmt.Sprintf("  install -m 600 /dev/null /path/to/fleet-enroll.token\n  # securely write this one-time token to the file: %s\n\n", server.EnrollSecret)
			note = "The enrollment file is removed after successful authentication. Re-mint with 'fleet server enroll-token " + server.Name + "'."
		}
		return fmt.Sprintf(
			"To install the agent on %s, download fleet-agent_%s for your OS/arch from\n"+
				"https://github.com/%s/releases. Verify the controller fingerprint shown by\n"+
				"'fleet key fingerprint', then run:\n\n%s"+
				"  fleet-agent reverse --controller <this-controller-address> --server-name %s --controller-fingerprint <verified-SHA256-fingerprint> --enroll-token-file /path/to/fleet-enroll.token\n\n"+
				"%s",
			server.Name, ver, agentGitHubRepo, enrollSetup, server.Name, note,
		)
	default:
		return fmt.Sprintf(
			"To install the agent on %s, download fleet-agent_%s for your OS/arch from\n"+
				"https://github.com/%s/releases and run:\n\n"+
				"  fleet-agent serve --listen 0.0.0.0:2222\n\n"+
				"Add it to your init system and ensure port 2222 is reachable.\n"+
				"Then run: fleet server reconnect %s",
			server.Name, ver, agentGitHubRepo, server.Name,
		)
	}
}

type agentLinuxTarget struct {
	name string
	arch string
}

var agentLinuxTargets = []agentLinuxTarget{
	{name: "linux-amd64", arch: "amd64"},
	{name: "linux-arm64", arch: "arm64"},
	{name: "linux-armv7", arch: "armv7"},
}

type agentArtifactDownloader func(context.Context, string) ([]byte, error)

const maxAgentArtifactBytes = 512 << 20

func downloadVerifiedAgentBinaries(ctx context.Context, rawVersion string, downloader agentArtifactDownloader) (map[string][]byte, error) {
	manifest, err := update.Fetch(ctx, update.DefaultManifestURL)
	if err != nil {
		return nil, fmt.Errorf("fetch release manifest: %w", err)
	}
	if downloader == nil {
		downloader = downloadApprovedAgentURL
	}
	return verifyAgentBinaries(ctx, rawVersion, manifest, downloader, update.SigningPublicKey())
}

func verifyAgentBinaries(ctx context.Context, rawVersion string, manifest update.Manifest, downloader agentArtifactDownloader, publicKeyText string) (map[string][]byte, error) {
	versionTag := strings.TrimSpace(rawVersion)
	if !strings.HasPrefix(versionTag, "v") {
		versionTag = "v" + versionTag
	}
	versionNoV := strings.TrimPrefix(versionTag, "v")
	if versionNoV == "" || strings.ContainsAny(versionNoV, "/\\_") {
		return nil, fmt.Errorf("invalid agent release version %q", rawVersion)
	}
	entries, ok := manifest.AgentBinaries[versionTag]
	if !ok {
		return nil, fmt.Errorf("agent release %s is absent from manifest", versionTag)
	}
	var publicKey minisign.PublicKey
	if err := publicKey.UnmarshalText([]byte(strings.TrimSpace(publicKeyText))); err != nil {
		return nil, fmt.Errorf("parse embedded minisign key: %w", err)
	}

	verified := make(map[string][]byte, len(agentLinuxTargets))
	for _, target := range agentLinuxTargets {
		info, ok := entries[target.name]
		if !ok {
			return nil, fmt.Errorf("incomplete agent release matrix: missing %s", target.name)
		}
		expectedURL := fmt.Sprintf("https://github.com/%s/releases/download/%s/fleet-agent_%s_linux_%s.tar.gz", agentGitHubRepo, versionTag, versionNoV, target.arch)
		if info.URL != expectedURL || info.Signature != expectedURL+".minisig" {
			return nil, fmt.Errorf("agent %s URLs are not bound to product, version, and target", target.name)
		}
		if len(info.SHA256) != sha256.Size*2 || info.Size <= 0 || info.Size > maxAgentArtifactBytes {
			return nil, fmt.Errorf("agent %s has invalid checksum or size metadata", target.name)
		}
		archive, err := downloader(ctx, info.URL)
		if err != nil {
			return nil, fmt.Errorf("download %s: %w", target.name, err)
		}
		if int64(len(archive)) != info.Size {
			return nil, fmt.Errorf("agent %s size mismatch", target.name)
		}
		signature, err := downloader(ctx, info.Signature)
		if err != nil {
			return nil, fmt.Errorf("download %s signature: %w", target.name, err)
		}
		if !minisign.Verify(publicKey, archive, signature) {
			return nil, fmt.Errorf("agent %s signature verification failed", target.name)
		}
		var parsed minisign.Signature
		if err := parsed.UnmarshalText(signature); err != nil {
			return nil, fmt.Errorf("parse %s signature: %w", target.name, err)
		}
		expectedComment := fmt.Sprintf("cenvero-fleet fleet-agent %s %s", versionTag, target.name)
		if parsed.TrustedComment != expectedComment {
			return nil, fmt.Errorf("agent %s signature binding mismatch", target.name)
		}
		digest := sha256.Sum256(archive)
		if !strings.EqualFold(hex.EncodeToString(digest[:]), info.SHA256) {
			return nil, fmt.Errorf("agent %s checksum mismatch", target.name)
		}
		binary, err := extractVerifiedAgentBinary(archive)
		if err != nil {
			return nil, fmt.Errorf("extract %s: %w", target.name, err)
		}
		verified[target.name] = binary
	}
	return verified, nil
}

func downloadApprovedAgentURL(ctx context.Context, rawURL string) ([]byte, error) {
	if err := validateAgentReleaseURL(rawURL); err != nil {
		return nil, err
	}
	data, err := update.DownloadApprovedURL(ctx, rawURL,
		"github.com", "release-assets.githubusercontent.com", "objects.githubusercontent.com")
	if err != nil {
		return nil, err
	}
	if len(data) > maxAgentArtifactBytes {
		return nil, fmt.Errorf("release payload exceeds %d bytes", maxAgentArtifactBytes)
	}
	return data, nil
}

func validateAgentReleaseURL(rawURL string) error {
	parsed, err := url.Parse(rawURL)
	if err != nil || parsed.Scheme != "https" || parsed.User != nil {
		return fmt.Errorf("refusing non-HTTPS or credentialed release URL")
	}
	switch strings.ToLower(parsed.Hostname()) {
	case "github.com", "release-assets.githubusercontent.com", "objects.githubusercontent.com":
		return nil
	default:
		return fmt.Errorf("refusing unapproved release host %q", parsed.Hostname())
	}
}

func extractVerifiedAgentBinary(archive []byte) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewReader(archive))
	if err != nil {
		return nil, err
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		header, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if header.Typeflag != tar.TypeReg || filepath.Base(header.Name) != "fleet-agent" {
			continue
		}
		binary, err := io.ReadAll(io.LimitReader(tr, maxAgentArtifactBytes+1))
		if err != nil {
			return nil, err
		}
		if len(binary) == 0 || len(binary) > maxAgentArtifactBytes {
			return nil, fmt.Errorf("invalid extracted fleet-agent size")
		}
		return binary, nil
	}
	return nil, fmt.Errorf("fleet-agent binary not found in archive")
}

func buildVerifiedBinaryInstallScript(server ServerRecord, sudo, serviceName string, tempBins map[string]string, tempServicePath, tempKeysPath, tempScriptPath string) string {
	lines := []string{
		"#!/bin/sh", "set -eu",
		"SERVICE_NAME=" + shellQuote(serviceName),
		"STATE_DIR=" + shellQuote(defaultStateDir),
		"CONFIG_DIR=" + shellQuote(defaultConfigDir),
		"BIN_DIR=" + shellQuote(defaultAgentBinDir),
		"BIN_PATH=" + shellQuote(defaultAgentBinaryPath),
		"AMD64_BIN=" + shellQuote(tempBins["linux-amd64"]),
		"ARM64_BIN=" + shellQuote(tempBins["linux-arm64"]),
		"ARMV7_BIN=" + shellQuote(tempBins["linux-armv7"]),
		"case \"$(uname -m)\" in",
		"  x86_64|amd64) SOURCE=\"$AMD64_BIN\" ;;",
		"  aarch64|arm64) SOURCE=\"$ARM64_BIN\" ;;",
		"  armv7l|armv7) SOURCE=\"$ARMV7_BIN\" ;;",
		"  *) echo \"unsupported architecture\" >&2; exit 1 ;;",
		"esac",
	}
	lines = append(lines, buildAgentSetupLines(sudo, serviceName, "\"$SOURCE\"", tempServicePath, tempKeysPath)...)
	lines = append(lines,
		"rm -f "+shellQuote(tempServicePath)+" "+shellQuote(tempKeysPath)+" "+shellQuote(tempScriptPath)+" \"$AMD64_BIN\" \"$ARM64_BIN\" \"$ARMV7_BIN\"",
		"echo \""+version.ProductName+" agent installed on "+server.Name+" (controller-verified artifact)\"",
	)
	return strings.Join(lines, "\n") + "\n"
}

func buildLocalBinaryInstallScript(server ServerRecord, sudo, serviceName, tempBinPath, tempServicePath, tempKeysPath, tempScriptPath string) string {
	lines := []string{
		"#!/bin/sh",
		"set -eu",
		"SERVICE_NAME=" + shellQuote(serviceName),
		"STATE_DIR=" + shellQuote(defaultStateDir),
		"CONFIG_DIR=" + shellQuote(defaultConfigDir),
		"BIN_DIR=" + shellQuote(defaultAgentBinDir),
		"BIN_PATH=" + shellQuote(defaultAgentBinaryPath),
		"",
	}
	lines = append(lines, buildAgentSetupLines(sudo, serviceName, shellQuote(tempBinPath), tempServicePath, tempKeysPath)...)
	lines = append(lines,
		"rm -f "+shellQuote(tempServicePath)+" "+shellQuote(tempKeysPath)+" "+shellQuote(tempBinPath)+" "+shellQuote(tempScriptPath),
		"echo \""+version.ProductName+" agent installed on "+server.Name+" (dev build)\"",
	)
	return strings.Join(lines, "\n") + "\n"
}

func buildAgentSetupLines(sudo, serviceName, binarySource, tempServicePath, tempKeysPath string) []string {
	return []string{
		sudo + "mkdir -p \"$BIN_DIR\" \"$STATE_DIR\" \"$CONFIG_DIR\"",
		sudo + "install -m 0755 " + binarySource + " \"$BIN_PATH\"",
		sudo + "install -m 0644 " + shellQuote(tempServicePath) + " /etc/systemd/system/" + shellQuote(serviceName) + ".service",
		sudo + "install -m 0600 " + shellQuote(tempKeysPath) + " \"$STATE_DIR/authorized_keys\"",
		sudo + "systemctl daemon-reload",
		sudo + "systemctl enable --now " + shellQuote(serviceName) + ".service",
	}
}

func buildAgentTeardownScript(serviceName, sudo, selfPath string) string {
	if serviceName == "" {
		serviceName = defaultServiceName
	}
	lines := []string{
		"#!/bin/sh",
		"set -eu",
		"SERVICE_NAME=" + shellQuote(serviceName),
		"",
		sudo + "systemctl disable --now \"$SERVICE_NAME\".service 2>/dev/null || true",
		sudo + "rm -f /etc/systemd/system/\"$SERVICE_NAME\".service",
		sudo + "systemctl daemon-reload",
		sudo + "rm -rf " + shellQuote(defaultAgentBinDir),
		sudo + "rm -rf " + shellQuote(defaultStateDir) + " " + shellQuote(defaultConfigDir),
		"rm -f " + shellQuote(selfPath),
		"echo \"" + version.ProductName + " agent removed\"",
	}
	return strings.Join(lines, "\n") + "\n"
}
