name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages-deployment
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.actor != 'cenvero-bot'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v5
